Nonablog/Blog/urls.py
from django.urls import path,include
from .views import *

app_name ='blog'

urlpatterns = [
    path('',blogs.as_view(),name='blog_home'),
    path('<int:pk>',blogs_single.as_view(),name='single'),
    path('addpost/',add_post,name='addpost'),
    path('category/<str:cat_name>',blogs.as_view(),name='category'),
    path('search/',blog_search,name='search'),
]

Nonablog/Mainweb/urls.py
from django.urls import path,include
from .views import *

app_name ='mainweb'

urlpatterns = [
    path('',index_viwe,name='index'),
    path('contact',contact_viwe,name='contact'),
    path('about',about_viwe,name='about'),
    path('elements',elements_viwe,name='elements'),
]

Nonablog/Nonablog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Mainweb.urls')),
    path('account/',include('accounts.urls')),
    path('blog/',include('Blog.urls')),
    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), 
        name='password_change'),

   path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
     name='password_reset_done'),

   path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
   
   path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
   path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
     name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Nonablog/Blog/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL

class Category(models.Model):
    name = models.CharField(max_length=223)
    
    def __str__(self) :
        return self.name

class Post(models.Model):
    image = models.ImageField(default='img/blog/cat-widget1.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    # tags = 
    category =models.ManyToManyField(Category) 
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
   
    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

Nonablog/Blog/forms.py
from .models import Post
from django import forms


class AddNewPost(forms.ModelForm):
    class Meta:
        model = Post
        fields =('image','author','title','content','counted_views','category','status')

Nonablog/Blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post
from django.views.generic import ListView , DetailView
from django.http import HttpResponse
from .forms import *
from django.core.paginator import Paginator ,PageNotAnInteger,EmptyPage

class blogs(ListView):
    model=Post
    template_name='blogs/blog-home.html'
    paginate_by = 2

    
    def get_queryset(self):
        return Post.objects.filter(status=1)


class blogs_single(DetailView):
    model=Post
    template_name='blogs/blog-single.html'
    
def add_post(request):
    if request.method == 'POST':
        form = AddNewPost(request.POST)
        if form.is_valid():
            form.save(commit=False)
            obj = form.instance
            return redirect('/')
        return HttpResponse(f"{form.errors}")    
    
    form = AddNewPost('blog/letest_post.html')
    context={'form':form}
    return render(request,'blogs/add_post.html',context)

def blog_search(request):
    posts=Post.objects.filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts=posts.filter(content__contains=s)
    context={'object_list':posts}
    return render(request,'blogs/blog-home.html',context)

Nonablog/templates/blogs/add_post.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<title>Add Post</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #03</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
						<div class="d-flex">
							<div class="w-100">
								<h3 class="mb-4">Sign In</h3>
							</div>
							<div class="w-100">
								<p class="social-media d-flex justify-content-end">
									<a href="#"
										class="social-icon d-flex align-items-center justify-content-center"><span
											class="fa fa-facebook"></span></a>
									<a href="#"
										class="social-icon d-flex align-items-center justify-content-center"><span
											class="fa fa-twitter"></span></a>
								</p>
							</div>
						</div>
						<form method="post" action="" class="login-form">
							{% csrf_token %}
							{{ form.as_p }}
							<div class="form-group d-flex align-items-center">
								</div>
								<div class="w-100 d-flex justify-content-end">
									<button type="submit" class="btn btn-primary rounded submit">post</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/popper.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

Nonablog/templates/blogs/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tag %}

<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">

			<div class="col-lg-8 posts-list">
				{% for post in object_list %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">

							<li><a href="#">{{ post.category.all|join:"," }}</a></li>
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ post.author }}</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:"M d, Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_views }} Views</a>
								<span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{{ post.image.url }}" alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:single' pk=post.id %}">
							<h3>
								{{ post.title }}
							</h3>
						</a>
						<p class="excert">
							{{ post.content|truncatechars:200 }}
						</p>
						<a href="{% url 'blog:single' pk=post.id %}" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}
           
				<div style="text-align: center;">
					<span class="step-links">
						{% if page_obj.has_previous %}
							<a href="?page=1">&laquo; first</a>
							<a href="?page={{ page_obj.previous_page_number }}">previous</a>
						{% endif %}
				
						<span class="current">
							Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
						</span>
				
						{% if page_obj.has_next %}
							<a href="?page={{ page_obj.next_page_number }}">next</a>
							<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
						{% endif %}
					</span>
				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="mb-5">
						<form action="{% url 'blog:search' %}" method="get">
							<div class="input-group">
								<input type="text" name="s" class="form-control form-control-lg" placeholder="Keyword">
								<div class="input-group-append">
									<span class="input-group-text bg-transparent text-primary"><i
											class="fa fa-search"></i></span>
								</div>
							</div>
						</form>
					</div>
					{% last_post %}
					{% categore_tag %}
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}

Nonablog/templates/blogs/blog-single.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load blog_tag %}
<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{ post.title }}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'mainweb:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:blog_home' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span> <a href="{% url 'blog:single' pk=post.id %}"> Blog Details Page</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{ post.image.url }}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							<li><a href="#">{{ post.category.all|join:"," }}</a></li>
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ post.author }}</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:"M d, Y" }}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">1.2M Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{ post.title }}</h3>
						<p class="excert">
						   {{ post.content }}
						</p>

					</div>
					<div class="col-lg-12">
						<div class="quotes">
							MCSE boot camps have its supporters and its detractors. Some people do not understand
							why you should have to spend money on boot camp when you can get the MCSE study
							materials yourself at a fraction of the camp price. However, who has the willpower to
							actually sit through a self-imposed MCSE training.
						</div>
						<div class="row mt-30 mb-30">
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="">
							</div>
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="">
							</div>
							<div class="col-lg-12 mt-30">
								<p>
									MCSE boot camps have its supporters and its detractors. Some people do not
									understand why you should have to spend money on boot camp when you can get the
									MCSE study materials yourself at a fraction of the camp price. However, who has
									the willpower.
								</p>
								<p>
									MCSE boot camps have its supporters and its detractors. Some people do not
									understand why you should have to spend money on boot camp when you can get the
									MCSE study materials yourself at a fraction of the camp price. However, who has
									the willpower.
								</p>
							</div>
						</div>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="#">
									<h4>Space The Final Frontier</h4>
								</a>
							</div>
						</div>
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="#">
									<h4>Telescopes 101</h4>
								</a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}" alt=""></a>
							</div>
						</div>
					</div>
				</div>
				<div class="comments-area">
					<h4>05 Comments</h4>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Emilly Blunt</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c2.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Elsie Cunningham</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c3.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Annie Stephens</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c4.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Maria Luna</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c5.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Ina Hayes</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form>
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" id="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" id="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
						</div>
						<div class="form-group">
							<input type="text" class="form-control" id="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>
						</div>
						<a href="#" class="primary-btn text-uppercase">Post Comment</a>
					</form>
				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget user-info-widget">
						<img src="{% static 'img/blog/user-info.png' %}" alt="">
						<a href="#">
							<h4>Charlie Barber</h4>
						</a>
						<p>
							Senior blog writer
						</p>
						<ul class="social-links">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-github"></i></a></li>
							<li><a href="#"><i class="fa fa-behance"></i></a></li>
						</ul>
						<p>
							Boot camps have its supporters andit sdetractors. Some people do not understand why you
							should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
							andits detractors.
						</p>
					</div>
					{% last_post %}
					{% categore_tag %}
					<div class="single-sidebar-widget newsletter-widget">
						<h4 class="newsletter-title">Newsletter</h4>
						<p>
							Here, I focus on a range of items and features that we use in life without
							giving them a second thought.
						</p>
						<div class="form-group d-flex flex-row">
							<div class="col-autos">
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
										</div>
									</div>
									<input type="text" class="form-control" id="inlineFormInputGroup"
										placeholder="Enter email" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Enter email'">
								</div>
							</div>
							<a href="#" class="bbtns">Subcribe</a>
						</div>
						<p class="text-bottom">
							You can unsubscribe at any time
						</p>
					</div>
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}

Nonablog/templates/blogs/category.html
{% load static %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Categories</h4>
    {% for name,count in categoris.items %}
    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
           <p><a href="{% url 'blog:category' cat_name=name %}">{{name}}</a></p>
           <p>{{count}}</p>
        </li>
    </ul>
    {% endfor %}
</div>

Nonablog/templates/blogs/latest_post.html
{% load static %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div style="text-align: center;" class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list  flex-row align-items-center">
            <div class="details">
                <a href="{% url 'blog:single' pk=post.id %}">
                    <h6 style="font-size: 22px;">{{post.title}}</h6>
                </a>
            </div>
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="" style="margin-left: 50px;padding-right: 100px">
            </div>
        </div>
        {% endfor %}
    </div>
</div>