Nonablog/Blog/urls.py
from django.urls import path,include
from .views import *

app_name ='blog'

urlpatterns = [
    path('',blogs.as_view(),name='blog_home'),
    path('<int:pk>',blogs_single.as_view(),name='single'),
    path('addpost/',add_post,name='addpost'),
    path('category/<str:cat_name>',blogs.as_view(),name='category'),
    path('search/',blog_search,name='search'),
]

Nonablog/Mainweb/urls.py
from django.urls import path,include
from .views import *

app_name ='mainweb'

urlpatterns = [
    path('',index_viwe,name='index'),
    path('contact',contact_viwe,name='contact'),
    path('about',about_viwe,name='about'),
    path('elements',elements_viwe,name='elements'),
]

Nonablog/Nonablog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Mainweb.urls')),
    path('account/',include('accounts.urls')),
    path('blog/',include('Blog.urls')),
    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), 
        name='password_change'),

   path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
     name='password_reset_done'),

   path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
   
   path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
   path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
     name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Nonablog/accounts/urls.py
from django.urls import path,include
from .views import *


app_name ='accounts'

urlpatterns = [
   path('login',login_view,name='login'),
   path('logout',logout_view,name='logout'),
   path('signup',signup_user,name='signup'),
   
   
]

Nonablog/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser , BaseUserManager
from .manager import AccountManager

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email',max_length=60,unique=True)
    username = models.CharField(max_length=30,unique=True)
    data_joined = models.DateTimeField(verbose_name='data joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    user_image = models.ImageField(default='img/blog/cat-widget1.jpg')
 
    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]
    
    def __str__(self):
        return self.username
    
    # یک تابع برای پرمیشن یوزر که ادمین است یا نه
    def has_perm(self, perm, obj=None):
        return self.is_admin
    def has_module_perms(self, app_label):
        return True

Nonablog/accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import authenticate
from .models import Account

class registerform(UserCreationForm):
    email = forms.EmailField(max_length=255)

    class Meta:
        model = Account
        fields = ('email' , 'username' , 'password1' , 'password2' )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()  
        
        try:
            account = Account.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"Email {email} is already use.")    
    
    def clean_username(self):
        username = self.cleaned_data['username'] 
        
        try:
            account = Account.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"username {username} is already use.")   

class Userlogin(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

Nonablog/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate ,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import registerform ,Userlogin
from django.http import HttpResponse


def signup_user(request ,*args, **kwargs):
    user=request.user
    if user.is_authenticated:
        return HttpResponse(f"you are already register with"+ str(user.email))
    context={}
    if request.POST:
            form=registerform(request.POST)
            if form.is_valid():
                form.save()
                email = form.cleaned_data.get('email').lower()
                password = form.cleaned_data.get('password1')
                account = authenticate(email = email ,password = password)
                login(request,account)

                return redirect('/')
            else:
                context['registration_form']=form 
    else:
        form = registerform()
        context['registration_form'] = form 
    
    return render(request,'accounts/signup.html',context)


def login_view(request, *args, **kwargs):
	context = {}

	user = request.user
	if user.is_authenticated: 
		return redirect("/")

	destination = get_redirect_if_exists(request)
	print("destination: " + str(destination))

	if request.POST:
		form = Userlogin(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				login(request, user)
				if destination:
					return redirect(destination)
				return redirect("/")

	else:
		form = Userlogin()

	context['login_form'] = form

	return render(request, "accounts/login.html", context)


def get_redirect_if_exists(request):
	redirect = None
	if request.GET:
		if request.GET.get("next"):
			redirect = str(request.GET.get("next"))
	return redirect


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')    




def repassword_user(request):
    pass

Nonablog/templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<title>Login </title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login </h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
						<div class="d-flex">
							<div class="w-100">
								<h3 class="mb-4">Sign In</h3>
							</div>
							<div class="w-100">
								<p class="social-media d-flex justify-content-end">
									<a href="#"
										class="social-icon d-flex align-items-center justify-content-center"><span
											class="fa fa-facebook"></span></a>
									<a href="#"
										class="social-icon d-flex align-items-center justify-content-center"><span
											class="fa fa-twitter"></span></a>
								</p>
							</div>
						</div>
						<form method="post" action="{% url 'accounts:login' %}" class="login-form">
							{% csrf_token %}
							<div class="form-group">
								<div class="icon d-flex align-items-center justify-content-center"><span
										class="fa fa-user"></span></div>
								<input type="email" name="email" class="form-control rounded-left" placeholder="Email"
									required>
							</div>
							<div class="form-group">
								<div class="icon d-flex align-items-center justify-content-center"><span
										class="fa fa-lock"></span></div>
								<input type="password" name="password" class="form-control rounded-left"
									placeholder="Password" required>
							</div>
							<div class="form-group d-flex align-items-center">
								<div class="w-100">
									<label class="checkbox-wrap checkbox-primary mb-0">Save Password
										<input type="checkbox" checked>
										<span class="checkmark"></span>
									</label>
								</div>
								<div class="w-100 d-flex justify-content-end">
									<button type="submit" class="btn btn-primary rounded submit">Login</button>
								</div>
							</div>
							{% for field in login_form %}
							<p>
							{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
							{% endfor %}
							</p>
							{% endfor %}
							{% if login_form.non_field_errors %}
							<div style="color: red">
							<p>{{login_form.non_field_errors}}</p>
							</div>
			
							{% endif %}
							<div class="form-group mt-4">
								<div class="w-100 text-center">
									<p class="mb-1">Don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
									<p><a href="{% url 'password_reset' %}">Reset password</a></p>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/popper.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

Nonablog/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>  
</form>


{% endblock %}

Nonablog/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been Updated.</p>
	</div>
</div>

{% endblock %}

Nonablog/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

Nonablog/templates/accounts/password_reset_done.html
<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'mainweb:index' %}">Return to home page</a></p>
	</div>
</div>

Nonablog/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Open-Chat Team
{% endautoescape %}

Nonablog/templates/accounts/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true" >
  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" >Send reset email</button>  
</form>



{% endblock %}

Nonablog/templates/accounts/signup.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<title>Sign up 03</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
						<div class="d-flex">
							<div class="w-100">
								<h3 class="mb-4" style="text-align: center">Sign up</h3>
							</div>
						</div>
						<form method="post" action="{% url 'accounts:signup' %}" class="login-form">
							{% csrf_token %}
							<div class="form-group">
								<div class="icon d-flex align-items-center justify-content-center"><span
										class="fa fa-user"></span></div>
								<input type="email" name="email" class="form-control rounded-left" placeholder="Email"
									required>
							</div>
							<div class="form-group">
								<div class="icon d-flex align-items-center justify-content-center"><span
										class="fa fa-user"></span></div>
								<input type="text" name="username" class="form-control rounded-left"
									placeholder="Username" required>
							</div>
							<div class="form-group">
								<div class="icon d-flex align-items-center justify-content-center"><span
										class="fa fa-lock"></span></div>
								<input type="password" name="password1" class="form-control rounded-left"
									placeholder="Password" required>
							</div>
							<div class="form-group">
								<div class="icon d-flex align-items-center justify-content-center"><span
										class="fa fa-lock"></span></div>
								<input type="password" name="password2" class="form-control rounded-left"
									placeholder="Confirm Password" required>
							</div>
							<div class="form-group d-flex align-items-center">
								<div class="w-100">
									<label class="checkbox-wrap checkbox-primary mb-0">Save Password
										<input type="checkbox" checked>
										<span class="checkmark"></span>
									</label>
								</div>
								<div class="w-100 d-flex justify-content-end">
									<button type="submit" class="btn btn-primary rounded submit">Sign up</button>
								</div>


							</div>
							{% for field in registration_form %}
							<p>
								{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
							{% endfor %}
							</p>
							{% endfor %}
							{% if registration_form.non_field_errors %}
							<div style="color: red">
								<p>{{registration_form.non_field_errors}}</p>
							</div>

							{% endif %}
							<div class="form-group mt-4">
								<div class="w-100 text-center">

								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/popper.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>